version: "3.7"

networks:
  cassbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.6.0.0/16

configs:
  first_node:
    file: ./config/node1.yaml

services:
  node1:
    image: cassandra:3.11.5
    ports:
      - 7000:7000
      - 9042:9042
    volumes:
      - ./data:/var/lib/cassandra
      - ./config/node1/cassandra.yaml:/etc/cassandra/cassandra.yaml
      - ./config/node1/cassandra-rackdc.properties:/etc/cassandra/cassandra-rackdc.properties
      - ./config/node1/cassandra-topology.properties:/etc/cassandra/cassandra-topology.properties
    environment:
      CASSANDRA_BROADCAST_ADDRESS: 10.6.0.5
    configs:
      - first_node
    networks:
      cassbr:
        ipv4_address: 10.6.0.5
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5

  node2:
    image: cassandra:3.11.5
    # ports:
    #   - 7000:7000
    volumes:
      - ./config/node2/cassandra.yaml:/etc/cassandra/cassandra.yaml
      - ./config/node2/cassandra-rackdc.properties:/etc/cassandra/cassandra-rackdc.properties
      - ./config/node2/cassandra-topology.properties:/etc/cassandra/cassandra-topology.properties
    environment:
      CASSANDRA_BROADCAST_ADDRESS: 10.6.0.6
      CASSANDRA_SEEDS: 10.6.0.5 # first node
    depends_on:
      - node1
        
    networks:
      cassbr:
        ipv4_address: 10.6.0.6

  ui:
    image: metavige/cassandra-web
    ports:
      - 8081:3000
    environment:
      CASSANDRA_HOST: 10.6.0.5
      CASSANDRA_USER: cassandra
      CASSANDRA_PASSWORD: 123456
    networks:
      cassbr: